data-station:
  fdp-url: http://fdp

spring:
  application:
    name: fair-data-station
  main:
    banner-mode: off
    web-application-type: reactive
  datasource:
    url: jdbc:postgresql://postgres/fds
    username: postgres
    password: password
  flyway:
    locations: classpath:db/migration
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha

management:
  health:
    solr:
      enabled:  false
  info:
    defaults:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health, info, gateway
      cors:
        allowed-origins: "*"
        allowed-methods: "GET"
