name: "Code Style"

on:
  push:
  pull_request:

jobs:

  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Verify Maven and Java
        run: |
          mvn --version

      - name: Run Checkstyle
        run: |
          mvn -B checkstyle:checkstyle

  spotbugs:
    name: SpotBugs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Verify Maven and Java
        run: |
          mvn --version

      - name: Run SpotBugs
        run: |
          mvn -B spotbugs:check

  license-head:
    name: License Headers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Verify Maven and Java
        run: |
          mvn --version

      - name: Check license
        run: |
          mvn -B license:check
